# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fd48884b18552d403f022c8bc24e1b3a07d27eabd5794c08f8866fc946738066060f5f1f85de934fbdfa6626f1e2301131a924cceebc7bef69fd94794b5a8f6

test:
  secret_key_base: f2a9d858e161f13455e56b35b98c16d9cd380759bc847502be6492302c0a4060898765145f4d7f4840a21e1e7faffad15a85197f378796310e831c88eb0f5c12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
